### ISSUE TITLE
Inline directive does  not work

### ISSUE THREAD

**Issue by hlzr** [sciunto-org/ikiwiki-pandoc#11]
The inline directive does not work with the ikiwiki-pandoc plugin (unless I am doing something wrong).

When I insert a directive (which works on an ikiwiki processed markdown page) like 

    [[!inline  pages="Blog/*" archive="yes" rootpage="Blog"]]

the following is all that is generated:

    ...
    <div id="pagebody">
        <section id="content" role="main">
            <div id="0" class="inline">
            </div>
        </section>
    </div>
    ...

If this is not a bug, perhaps consider adding it as a caveat to the documentation.

Thanks for the time spent on this plugin!

-Kevin

**Comment by bk** [comment]
Hello Kevin,

You are indeed right that the inline directive does not work properly in pandoc-processed pages. Raw inlines do work, e.g.

    [[!inline raw="yes" pages="ovipara/vertebrata/aves/*"]]

which means that the plugin is being called at the proper place, but the more common form of inline with `archive="yes"` for some reason fails. I will need to look further into this.

**Comment by bk** [comment]
I have now investigated the issue further. The reason that content is dropped is the somehwat unfortunate method the inline plugin uses for inserting the content into the page:

1. In the `preprocess` hook, which happens before the content has been transformed into HTML, it assembles the pages to be rendered and transforms them into HTML. Unless we're dealing with raw or nested inlines, these snippets of HTML are not inserted into the page at once. Instead, the plugin inserts placeholders which look like `<div class="inline" id="XX"></div>`, where `XX` the number of the snippet to be placed there.
2. The markup processor (in our case `pandoc`) now processes the base page, which no longer contains `inline` directives, but instead contains these placeholders.
3. In the `format` hook, the inline plugin comes onto the scene again and replaces the placeholders with their corresponding snippets. This is done with a regular expression replacement.

The problem with this process from our perspective is that pandoc parses and re-outputs the placeholders. In the process, their `id` and `class` attributes are reversed. As a consequence, the regular expression fails to match and no snippets are in fact inserted.

In my opinion, the placeholder pattern in the inline plugin should be changed so as to prevent such problems, which no doubt affect other plugins as well. But even if this would be done, we still would have to detect inline placeholders in the pandoc plugin before pandoc is run, and protect them somehow from being mangled, since many people will have older versions of the inline plugin which do not contain this putative fix. I'll try to implement this during the weekend.

**Comment by bk** [comment]
I've now fixed the issue by protecting inline placeholders from being processed by pandoc. The fix is in release v0.4.2.

**Comment by sciunto** [comment]
Thanks @bk !

**Comment by hlzr** [comment]
Thank you very much!
