### ISSUE TITLE
img directive doesn't work on pages that are processed by ikiwiki-pandoc

### ISSUE THREAD

**Issue by openmedi** [sciunto-org/ikiwiki-pandoc#12]
OS X 10.11.4
ikiwiki: 3.20150614 (via pkgsrc)

I realized that the [img directive](https://ikiwiki.info/ikiwiki/directive/img/) is not working on pages that are processed with ikiwiki-pandoc. That migh simply by a limitation of the plugin, but it would be very nice if especially this directive would work, since I'd like to use the img directive for showing specific pages of pdf files without having to convert them first to images, rename them and so on.

Of course, it might also be a bug.

**Comment by bk** [comment]
The `[[!img]]` directive works for me in pandoc-processed pages on my own personal wiki. I also tried it on a fresh install of ikiwiki + ikiwiki-pandoc, and it worked there as well. So I'm pretty sure that the problem is caused by some kind of misconfiguration on your end.

You mention pdf processing specifically. Does the directive work for other image types? If so, you might have to add or change the `img_allowed_formats` setting in your `.setup` file so as to add `pdf` to your allowed formats. If it is present, but pdf processing fails anyway (while, e.g., jpg works), this might be because `ghostscript` is missing on your machine – this is an external program which ImageMagick uses for handling `pdf`, `ps` and `eps` files.

Do you get any error messages related to image processing when you run `ikiwiki --setup my.setup` or similar?

**Comment by bk** [comment]
Sorry, I forgot to check which ikiwiki version you were using. I can see that there have been [several changes](https://github.com/joeyh/ikiwiki/commits/master/IkiWiki/Plugin/img.pm) to the `img` plugin since version 3.2015061, among them the addition of the `img_allowed_formats` setting, so that is not really relevant to your case. Even so, after examining these changes they do not seem to me to be likely to have affected the usability of the directive on pandoc-backed pages. (But of course updating ikiwiki would be a good idea anyway).

**Comment by openmedi** [comment]
Indeed Image::Magick was "missing" because I had tried out perlbrew and the perl used didn't have imagemagick installed. I probably should've checked a little closer, but yeah, that is at least the "issue" with ikiwiki-pandoc.

>Of course, it might also be a bug.

Of course, might also be my own fault.
