### ISSUE TITLE
Inclusion into ikiwiki? Package for debian?

### ISSUE THREAD

**Issue by openmedi** [sciunto-org/ikiwiki-pandoc#18]
This is an issue, but one that's more meant as a starting point for discussion, than anything else. 

Some context first: I'm looking to get my local ikiwiki based wiki onto the web, so that I can interact with it, even when I'm not on my laptop. I researched and tried to get it to work on the shared hosting platform [nearly free speech](https://www.nearlyfreespeech.net/), but the allowed cpu time is not enough for a complex wiki such as mine. Next thing I looked into was [branchable](http://www.branchable.com/), the dedicated ikiwiki hosting platform, mantained by Joey Hess himself. Since I rely on your awesome plugin (and pandoc) to render most of my wiki's pages and their bibliographic references, [I was disappointed to see that branchable doesn't support any custom plugins, that aren't either a debian package or included into the main ikiwiki package.](http://www.branchable.com/forum/Custom_plugins__63__/)

This is what brings me here then: How easy or hard would it be and what would be the problems that come with trying to go either route? What are the reasons to avoid packaging and/or merging this plugin into ikiwikis main repo?

Since I'm mostly a user of software, I want to try to understand if it's worth it (for me and/or anybody else) to pursue an inclusion of ikiwiki-pandoc into something else. My assumption is, that branchable simply doesn't fit the bill for me if I need ikiwiki-pandoc, since I am not experienced enough to submit a patch to ikiwiki or go through the packaging of ikiwiki-pandoc without using significant amounts of my time up front to do so, since I would need to learn a lot of things, which means that a lot of other things would need to be put on my waiting list and that it would be better to try to find a different solution to put my notes on a server. However, I at least want to see if there's an upside (maybe even a significant one) to such a suggestion, which is why I opened this issue.

If in the future people are wondering why ikiwiki-pandoc is not merged with ikiwiki (main) and doesn't have its on debian package, than people could be pointed here.

**Comment by bk** [comment]
You raise four distinct issues, @openmedi:

1. **Easy hosting** of a fully functional ikiwiki site with custom plugins and web interface. This is currently rather difficult for the average user. The best option is probably to rent a small VPS (the cheapest offering by [Digital Ocean](https://digitalocean.com/) at $5/month is quite sufficient). The quickest way to address this issue would be to write detailed instructions about how to go about this.

2. **Creating a `.deb` package.** This is rather easy. It should be no problem for me to do this every time we change the module, and make the download available here through github.

3. **Inclusion in the official Ikiwiki project.** Since we are largely dependent upon a third-party markup processor, namely pandoc, I don't think we would fit inside the scope of core Ikiwiki, so this is probably not realistic. But of course it would do no harm to ask [Joey Hess](http://joeyh.name/) his opinion...

4. **Inclusion in Debian or other Linux distributions.** This is almost certainly possible but involves quite a bit of work and, more significantly, commitment for the future. I am not personally ready to do that, but perhaps someone else would like to step up?

Together, these questions suggest that ikiwiki-pandoc's threshold for adoption is too high, i.e. requires too much know-how on the part of the users of the module. In view of the fact that the userbase for markdown-related software is getting steadily wider and less technically sophisticated, we should do something to address that central issue.

**Comment by openmedi** [comment]
Thanks for your thoughtful answer!

> 1. Easy hosting

This is what I'll try. I've looked into Digital Ocean and [Vultr](https://www.vultr.com/) and since Vultr is offering basically the same as DC and also a trial month, I'll try to get it to work there. I might publish what I have learned in the [ikiwiki forums](http://ikiwiki.info/forum/) and/or might write up a proper how to which could be included in [the tips section of ikiwiwki](http://ikiwiki.info/tips/).

>2. Creating a .deb package

In regards to the problem raised (getting ikiwiki-pandoc to work at branchable), this might not be sufficient, since [Joey said](http://www.branchable.com/forum/Custom_plugins__63__/#comment-c8e29c83421b136429c2631f3bb60ece) that the package also had to be included into the debian distribution in order to for it to be available to the branchable customer. With that said, I think it might still be useful for the easy hosting issue.

>3. Inclusion in the official Ikiwiki project

On the other hand: ikiwiki itself is using an external markdown processor for the rendering itself, which can be changed in the setup file. It might make sense then, to think about if pandoc couldn't be one of those rendering engines.

>4. Inclusion in Debian or other Linux distributions

It's indeed a big commitment. I was also thinking that it might be useful to think about if packaging more than one plugin into one (e.g. ikiwiki-thridparty), so that it would be easy to install a bunch of ikiwikis awesome 3rd party plugins at once. This of course would need a knowledgable maintainer, which is why this will probably not happen.

* * *

I think you're right in saying that ikiwiki makes it kinda hard to use for a lot of users. It's a powerful tool that could provide a lot of value to a lot of people (not only developers or power users like me) if it would be a little bit simpler to set up and use. But how to address and discuss this further? It's obvious that an issue related to one plugin isn't the right venue, for this more general questions. The forums on the projects homepage are basically dead though and as far as I know, there aren't any mailinglists, etc.
