### ISSUE TITLE
Use of uninitialized value […] in pattern match (m//) at […]/pandoc.pm line 269.

### ISSUE THREAD

**Issue by openmedi** [sciunto-org/ikiwiki-pandoc#6]
That's the error I get when trying to rebuild my wiki after following the install instructions. I am using pkgsrc ikiwiki 3.20150614 and pandoc 1.16.0.1 from homebrew. I am on OS X 10.11.2.

And that's the line the error refers to in pandoc.pm:

```
my $mathopt = $1 if $config{pandoc_math} =~ /(\w+)/;
```

**Comment by bk** [comment]
That should be a warning rather than a fatal error. Does the rebuilding of the wiki stop when you get the error message?

I'll submit a pull request later today to prevent this, but as a workaround (and also because it is a good idea in itself) you can add the line

    pandoc_math => 'mathjax',

to the config options in your `*.setup` file. By the way, which Perl version are you using?

**Comment by bk** [comment]
PR #7 gets rid of the warning.

**Comment by openmedi** [comment]
It's the pkgsrc perl, version 5.22.0. Thanks for your work. It is indeed a warning, since my files are getting built. I do still have a problem to get the bibliography stuff working. I'll open another issue.

**Comment by sciunto** [comment]
I merged #7. Thank you.
