### ISSUE TITLE
pandoc style citations don't work

### ISSUE THREAD

**Issue by openmedi** [sciunto-org/ikiwiki-pandoc#8]
I am using pkgsrc ikiwiki 3.20150614 and pandoc 1.16.0.1 from homebrew. I am on OS X 10.11.2. I use the pkgsrc perl version 5.22.0.

When using pandoc to build my wiki pages, citations seem to be ignored completely.

**Comment by bk** [comment]
This works for me, so I suspect you have a configuration problem. Things to check for:

1. Have you specified `pandoc_bibliography` in the `*.setup` file? If so, have you specified an absolute path to the `.bib` file?
2. If the answer above is No, have you instead specified `bibliography` in the YAML meta block in the page, again preferably with an absolute path?
3. Is `pandoc-citeproc` configured in `*.setup` or present in your `$PATH`? (I do not use homebrew myself, but I am given to understand that `pandoc-citeproc` is a separate package which is not automatically installed when you install `pandoc`).
4. Does the `.bib` file contain syntax errors?
5. Are you absolutely certain that your files are being handled by pandoc rather than the default Markdown processor? I have found it to be easiest to separate them by extension, using `*.md` for pandoc and `*.mdwn` for the default processor. This is also a good idea because a few ikiwiki directives (i.e. commands surrounded by `[[!...]]`) do not work in pandoc-processed files.

If everything in the list checks out OK, it would be interesting to see your `*.setup` file and a sample page which fails.

**Comment by openmedi** [comment]
It indeed turned out to be a configuration error on my end: I had but my bib file my csl in single quotes, as  I thought the empty single quotes in my .setup suggested. Turns out, you shouldn't use quotes there. Thanks!

P.S.: I think it might be a good idea to present the caveats as regards to some ikiwiki derectives not working in the readme.

**Comment by bk** [comment]
Can you please clarify? The `.setup` file is just perl, so it makes no difference whether you use single or double quotes (as long as you're not doing any variable interpolation). How was it before, when it didn't work, and how did you change it to make it work?

**Comment by openmedi** [comment]
Here's how the relevant portion of the ```.setup``` looks after installing ```pandoc.pm``` and using ```ikiwiki --changesetup```:

```
# Path to default bibliography file
pandoc_bibliography: ''
# Path to CSL file (for references and bibliography)
pandoc_csl: ''
```

I assumed that these single quotes were ment to be filled instead of being replaced.

**Comment by bk** [comment]
Ah, you're using the YAML `.setup` format. Still, this is puzzling, since the presence or absence of surrounding quotes should not affect normal filenames in YAML: `/path/file.ext`, `'/path/file.ext'` and `"path/file.ext"` all represent the same string. (For the details on when quoting makes a difference, see the [YAML spec](http://www.yaml.org/spec/1.2/spec.html#id2786942)). Could you have inadvertently inserted a space before or after the filename, or something of the sort?

**Comment by openmedi** [comment]
I guess that's possible, too. I'm not sure what my error was, only that it was mine. Hehe. I'm very happy that it works now.
