### ISSUE TITLE
How to set locale (for bibliography) wiki wide

### ISSUE THREAD

**Issue by openmedi** [sciunto-org/ikiwiki-pandoc#9]
I am using pkgsrc ikiwiki 3.20150614 and pandoc 1.16.0.1 from homebrew. I am on OS X 10.11.2. I use the pkgsrc perl version 5.22.0.

I am a German speaking person and so my bibliographic needs are also German. For some reason my locators (e.g. "page" should be "Seite", "p." should "S.") are still in English, even though I've set my locale  in my ```.steup``` to ```de_DE.UTF-8```. Aso setting the locale via the lang variable (through yaml front matter) on a particular page doesn't seem to work und would also be in any case not prefered.

**Comment by bk** [comment]
Setting the language in the meta block of the page itself works for me. E.g.:

```yaml
---
title: Wahrscheinlichkeit, Wahrheit und Widerspruch
lang: de
...
```

Judging by the [pandoc-citeproc locale files](https://github.com/jgm/pandoc-citeproc/tree/master/locales), "de_DE" or "de_AT" would also work. But "de_DE.UTF-8" probably does not, since the "UTF-8" part is taken to be part of the locale code rather than the encoding.

As for overriding the default language globally, I can think of two different workarounds:

1. Let the `pandoc_command` configuration option point to a shell script which adds `-V lang:de` to any arguments it receives before calling pandoc with the result.
2. Let `pandoc_csl` in the config point to a language-specific CSL file. (If you don't have it at hand, it is normally easy to create yourself, by simply copying the original and adding/replacing `default-locale="de-DE"` in the top-level `<style ...>` tag – at least if your bibliography processor understands the attribute and knows where to find decent translations, which [pandoc-citeproc does](https://github.com/jgm/pandoc-citeproc/blob/7d0a286136117ec4dfde014372c0e2e46f359400/src/Text/CSL/Parser.hs#L103)).

That being said, it would be a nice feature if the default locale of citations and bibliography was configurable through the `.setup` file. It would be rather easy to add, so maybe if I get some time in the next few days...

**Comment by sciunto** [comment]
closed by #10 Many thanks @bk

**Comment by bk** [comment]
The above comment was not entirely correct: The additional parameter which should have been added in  the first workaround is `-M lang:de`, not `-V lang:de`.

I've now submitted PR #10 which makes the default language configurable through the `.setup` file.

**Comment by openmedi** [comment]
Thanks for all your great help @bk!
